### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by aw** [dbrgn/pinetime-rtic#6]
Hello,

I noticed there isn't a license specified anywhere in the repo, sources, README, or cargo file. Can you please add a license somewhere so others can build upon your work?

Thanks!

**Comment by dbrgn** [comment]
You're right, that was an oversight!

**Comment by dbrgn** [comment]
Done. Dual-licensed under MIT and Apache.

**Comment by aw** [comment]
Thank you!! 👍🏾
